FROM python:3.11-slim

WORKDIR /app

ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

COPY requirements.streamlit.txt .
RUN pip install --no-cache-dir -r requirements.streamlit.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]
